### PR TITLE
Updating hasMember comment with note on transitivity (fixes #29)

### LINKED ISSUE #29: Clarify transitivity of predicates
In mapping between PCDM and the DPLA MAP, a question arose as to whether hasMember is transitive.
For example, given:

```
_:a pcdm:hasMember _:b .
_:b pcdm:hasMember _:c .
```

It should be stated that it is not true that `_:a pcdm:hasMember _:c`  It may be valuable to have a `pcdm:hasChildOrDescendantMember` (or similar) predicate, but to be actually useful, it would need to be auto-created by the repository.  Otherwise we would have the etag resource vs representation state problem to the nth degree.

### LINKED ISSUE #36: AdministrativeSets and ldp:contains
Currently, AdministrativeSet is defined as a subset of ldp:Container and uses ldp:contains to link to Objects and Collections it contains.  This works fine when the expected repository structure is to use have AdministrativeSets be top-level containers with their Objects and Collections directly inside them:

```
/set1/object1
/set1/collection1
/set2/object2
/set2/collection2
```

But if you structure your repository with all resources at the top level (which I think we decided was a good practice to avoid having to change identifiers if a resource changed ownership from one AdministrativeSet to another):

```
/collection1
/collection2
/object1
/object2
/set1
/set2
```

Then the Objects and Collections aren't contained by the AdministrativeSet.  And Fedora will not let you create the triple `</set1> ldp:contains </object1>`, since ldp:contains is a server-managed predicate.

Should we be using a different property for belonging to an AdministrativeSet?

### PR DESCRIPTION
**Pull request by escowles**

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1:

**Comment by no-reply** [comment]
:+1:. It seems there's a stand-off about merging. But we're on three :+1:'s now. I'll merge this in an hour if no one cries foul by then. 

In the meanwhile, do we have a PR policy (loose or otherwise)?

**Comment by no-reply** [comment]
Excellent

**Comment by no-reply** [comment]
Looks like we may need 5, per https://github.com/duraspace/pcdm/issues/8#issue-76490564. The [current committers](https://github.com/duraspace/pcdm/wiki/PCDM-Committers) list has 10 people.

**Comment by kestlund** [comment]
:+1:

**Comment by daniel-dgi** [comment]
:+1: Looks good to me!

**Pull request merged**
