### PR TITLE
improve HTML display

### PR DESCRIPTION
**Pull request by acoburn**
This updates the `rdfs2html.xsl` stylesheet to make the HTML output somewhat nicer for `models#`, `use#` and `rights#`

Examples are here: 
- https://www.ats.amherst.edu/~acoburn/pcdm/models.rdf
- https://www.ats.amherst.edu/~acoburn/pcdm/rights.rdf
- https://www.ats.amherst.edu/~acoburn/pcdm/use.rdf

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1:

**Comment by azaroth42** [comment]
:+1: to a PCDM logo!

**Comment by awoods** [comment]
:+1: to this polish. Shall we wait on committing this update until we have a proper PCDM logo?

**Comment by daniel-dgi** [comment]
:+1: to logo indeed

**Comment by awoods** [comment]
?? https://www.facebook.com/PASUKANCIJANTUNGDEATHMETAL/photos/a.414234391974404.104827.132583080139538/414234635307713/?type=3&theater

**Comment by daniel-dgi** [comment]
ship it

**Comment by scossu** [comment]
:+1: for committing now as is. The logo seems to be a separate concern.

**Comment by awoods** [comment]
:+1: to committing now.
Follow-on issue created: https://github.com/duraspace/pcdm/issues/38

**Comment by jpstroop** [comment]
Late to the party, but I agree re: a logo.

**Comment by awoods** [comment]
Published `models` updated:
http://pcdm.org/models

**Comment by acoburn** [comment]
@awoods do you also plan to add the updated `rdfs2html.xsl` (and `assets/` dir) to the http://pcdm.org/use and http://pcdm.org/rights pages?

**Comment by awoods** [comment]
done

**Pull request merged**
