### PR TITLE
Removes pcdm:hasRelatedFile from `context.json`

### PR DESCRIPTION
**Pull request by no-reply**
pcdm:hasRelatedFile was removed from the RDF(S) in https://github.com/duraspace/pcdm/pull/31, but hung around in the JSON-LD context. 

Removing it from there, now.

The second commit (8eb09c9) removes unused namespaces and cleans up trailing whitespace.

### CODE REVIEW

**Comment by awoods** [comment]
Shouldn't "relatedFileOf" also go away? 
https://github.com/duraspace/pcdm/blob/remove-has-related-file/context.json#L27

**Comment by no-reply** [comment]
Thanks @awoods.

I removed the inverse relation and squashed the commits.

**Comment by escowles** [comment]
As long as we're tidying up, should we be declaring namespaces that are not used in the context?  Is it standard practice to include namespaces that you expect to be generally useful?

AFAICT, ldp, and rdf aren't actually used in the context (though they are used in the ontology of course).  There are also several namespaces that I don't think we're using anywhere: ebucore, foaf, gen, premis, and sweetjpl.

**Comment by no-reply** [comment]
@escowles I cleaned up the namespaces that aren't used. `ldp:` does appear in a couple of places. Otherwise, I think your list was correct.

Do we need some standard way of testing this context? It would help my confidence in making these changes if we had clear requirements that, ideally, could be checked automatically.

**Comment by escowles** [comment]
@no-reply -- my bad, I didn't expand the file all the way to the bottom so the LDP usage was still hidden.

I agree it would be great to automatically test the ontology files.  We could minimally test the RDF/XML by transforming it with the rdfs2html.xsl stylesheet.  Similarly, I'm sure we can find tools to validate the JSON is well-formed.  But neither of these would catch unused namespaces.

**Comment by azaroth42** [comment]
:+1: To test the context, you could write a little script that took known data, expanded and compacted it, then tested to see if it was the same as the input?

**Comment by awoods** [comment]
This PR looks good. Shall we move it forward while also creating a new issue for automating testing of the context?

**Comment by escowles** [comment]
+1 to merging this and handling automatic testing in a separate ticket.

**Comment by no-reply** [comment]
Yes. Though I think we are waiting on an additional :+1:, and whatever else is required by #44.

**Comment by no-reply** [comment]
(I guess not the additional :+1: anymore, due to @escowles).

**Comment by awoods** [comment]
...now we wait for 7 days :( ..or 7 days from: https://github.com/duraspace/pcdm/pull/45#issuecomment-186705081 which was 2 days ago.
Merge target: Feb 26th

**Comment by azaroth42** [comment]
In automated testing issue, can we also discuss automated merge/deploy? Scan the comment threads of PRs for sufficient +1s and no -1s, look at commit dates ... seems like an easy algorithm

**Comment by no-reply** [comment]
This one should be ready, per https://github.com/duraspace/pcdm/pull/45#issuecomment-187310563

**Pull request merged**
