### PR TITLE
Adding pcdm:Order class

### PR DESCRIPTION
**Pull request by escowles**
See https://docs.google.com/document/d/1x2ySLd6Oag_gsejXBPWV5AL2SFzS1swwCUk9N9isJVM/edit# (Multiple Orders section)

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1:

**Comment by scossu** [comment]
:+1:

**Comment by awoods** [comment]
See: https://github.com/duraspace/pcdm/pull/31#issuecomment-143043727

**Comment by jpstroop** [comment]
Why:

> Only for second and subsequent orders.

Isn't that going to get confusing? I have no doubt that the multiple orders use case will surface, but at that point it seems a little awkward to me that the different orders available would be related to the object in different ways. Is one order favored over the other? If so, that should be made clear. Maybe there's another reason for this that I'm missing? Otherwise the semantics seem less clear than they could be to me.

**Comment by jpstroop** [comment]
Ah. The `rdfs:comment` clears it up a bit. Maybe the name of the class should be `pcdm:AlternateOrder`?

**Comment by escowles** [comment]
The main reasoning for only using pcdm:Order for second and further orders is simplicity for single-order objects.  So calling it pcdm:AlternateOrder sounds good to me.

**Comment by escowles** [comment]
I've renamed the class to AlternateOrder and cleaned up the description.

**Comment by escowles** [comment]
@ruebot: I've rebased and now it'll merge cleanly!

**Comment by awoods** [comment]
:+1: 
...just need one more.

**Comment by azaroth42** [comment]
:+1: to pcdm:AlternateOrder

**Pull request merged**
