### PR TITLE
create aliases for type and id

### PR DESCRIPTION
**Pull request by acoburn**
Addresses #41

### CODE REVIEW

**Comment by escowles** [comment]
:+1:

**Comment by azaroth42** [comment]
:+1: Thanks @acoburn! Was going to do it, but only just got back to hotel from TPAC2015 where we agreed on it :)

**Comment by daniel-dgi** [comment]
:+1: noice

**Comment by jpstroop** [comment]
:+1:

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by DiegoPino** [comment]
Moral support :+1:

**Pull request merged**
