### PR TITLE
Address issue #12

### PR DESCRIPTION
**Pull request by ruebot**

### CODE REVIEW

**Comment by awoods** [comment]
Is this a common practice to define namespaces in an ontology that are not used therein?

**Comment by escowles** [comment]
:+1: -- I think it's good to define the namespace (even if not used in the ontology) to suggest the namespace prefix.

**Comment by azaroth42** [comment]
:ok_hand: No objection.

**Comment by ruthtillman** [comment]
FWIW I've been working through madsrdf lately and I noticed they did the same thing, but it's not used inside the document. Within the document they also use prefixes in the rdf:comment when referring to other elements, e.g. madsrdf:extendedAddress. Don't know if y'all feel like going that far. It seems like capitalization is serving right now for indication of the formal Class/Property term.

**Comment by DiegoPino** [comment]
:thumbsup: -- @ruebot  happy to see this

**Comment by scossu** [comment]
:+1:

**Pull request merged**
